/*
 * lcd_test.c
 *
 *  Created on: 24-Sept-2026
 *      Author: Lenovo
 */

#include "lcd_test.h"
#include "spi.h"   // gives hspi1, generated by CubeMX

extern SPI_HandleTypeDef hspi1;

#define LCD_CS_LOW()   HAL_GPIO_WritePin(LCD_CS_GPIO_Port, LCD_CS_Pin, GPIO_PIN_RESET)
#define LCD_CS_HIGH()  HAL_GPIO_WritePin(LCD_CS_GPIO_Port, LCD_CS_Pin, GPIO_PIN_SET)
#define LCD_DC_CMD()   HAL_GPIO_WritePin(LCD_DC_GPIO_Port, LCD_DC_Pin, GPIO_PIN_RESET)
#define LCD_DC_DATA()  HAL_GPIO_WritePin(LCD_DC_GPIO_Port, LCD_DC_Pin, GPIO_PIN_SET)
#define LCD_RST_LOW()  HAL_GPIO_WritePin(LCD_RST_GPIO_Port, LCD_RST_Pin, GPIO_PIN_RESET)
#define LCD_RST_HIGH() HAL_GPIO_WritePin(LCD_RST_GPIO_Port, LCD_RST_Pin, GPIO_PIN_SET)

static void LCD_WriteCommand(uint8_t cmd)
{
    LCD_DC_CMD();
    LCD_CS_LOW();
    HAL_SPI_Transmit(&hspi1, &cmd, 1, HAL_MAX_DELAY);
    LCD_CS_HIGH();
}

static void LCD_WriteData(uint8_t data)
{
    LCD_DC_DATA();
    LCD_CS_LOW();
    HAL_SPI_Transmit(&hspi1, &data, 1, HAL_MAX_DELAY);
    LCD_CS_HIGH();
}

static void LCD_WriteDataBuffer(uint8_t *buf, uint16_t len)
{
    LCD_DC_DATA();
    LCD_CS_LOW();
    HAL_SPI_Transmit(&hspi1, buf, len, HAL_MAX_DELAY);
    LCD_CS_HIGH();
}

static void LCD_HardReset(void)
{
    LCD_RST_HIGH();
    HAL_Delay(10);
    LCD_RST_LOW();
    HAL_Delay(10);
    LCD_RST_HIGH();
    HAL_Delay(120); // panel needs this settle time after reset
}

static void LCD_SetWindow(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1)
{
    uint8_t caset[4] = { (uint8_t)(x0 >> 8), (uint8_t)(x0 & 0xFF),
                          (uint8_t)(x1 >> 8), (uint8_t)(x1 & 0xFF) };
    uint8_t raset[4] = { (uint8_t)(y0 >> 8), (uint8_t)(y0 & 0xFF),
                          (uint8_t)(y1 >> 8), (uint8_t)(y1 & 0xFF) };

    LCD_WriteCommand(0x2A); // CASET - column address set
    LCD_WriteDataBuffer(caset, 4);

    LCD_WriteCommand(0x2B); // RASET - row address set
    LCD_WriteDataBuffer(raset, 4);

    LCD_WriteCommand(0x2C); // RAMWR - memory write follows
}

void LCD_Init(void)
{
    LCD_HardReset();

    LCD_WriteCommand(0x01); // Software reset
    HAL_Delay(150);

    LCD_WriteCommand(0x11); // Sleep out
    HAL_Delay(120);

    LCD_WriteCommand(0x3A); // Interface pixel format
    LCD_WriteData(0x55);    // 0x55 = 16-bit RGB565

    LCD_WriteCommand(0x36); // Memory access control (orientation/mirroring)
    LCD_WriteData(0xC8);    // if the test pattern looks flipped/mirrored, try 0xC0, 0x60, or 0xA0 here
    //4 -> 0100
    //8 -> 1000
    //C -> 1100

//    LCD_WriteCommand(0x21); // Display inversion ON
                             // NOTE: many ST7789 panels need this to show correct colors.
                             // If colors look like a photo negative, DELETE this line.
                             // If colors look washed out/wrong without it, KEEP it.

    LCD_WriteCommand(0x13); // Normal display mode on
    HAL_Delay(10);

    LCD_WriteCommand(0x29); // Display ON
    HAL_Delay(50);
}

void LCD_FillScreen(uint16_t color)
{
    LCD_SetWindow(0, 0, 200, 300);

    uint8_t hi = (uint8_t)(color >> 8);
    uint8_t lo = (uint8_t)(color & 0xFF);
    uint8_t line[240 * 2]; // one row's worth of RGB565 pixels

    for (int i = 0; i < 240; i++) {
        line[i * 2]     = hi;
        line[i * 2 + 1] = lo;
    }

    LCD_DC_DATA();
    LCD_CS_LOW();
    for (int row = 0; row < 320; row++) {
        HAL_SPI_Transmit(&hspi1, line, sizeof(line), HAL_MAX_DELAY);
    }
    LCD_CS_HIGH();
}

void LCD_TestPattern(void)
{
    LCD_FillScreen(0xF800); // Red
    HAL_Delay(1000);
    LCD_FillScreen(0x07E0); // Green
    HAL_Delay(1000);
    LCD_FillScreen(0x001F); // Blue
    HAL_Delay(1000);
    LCD_FillScreen(0xFFFF); // White
    HAL_Delay(1000);
    LCD_FillScreen(0x0000); // Black
}
