/*
 * touch_test.c
 *
 *  Created on: 24-Sept-2026
 *      Author: Lenovo
 */

#include "touch_test.h"
#include "spi.h"   // gives hspi2, generated by CubeMX

extern SPI_HandleTypeDef hspi2;

#define TOUCH_CS_LOW()  HAL_GPIO_WritePin(TOUCH_CS_GPIO_Port, TOUCH_CS_Pin, GPIO_PIN_RESET)
#define TOUCH_CS_HIGH() HAL_GPIO_WritePin(TOUCH_CS_GPIO_Port, TOUCH_CS_Pin, GPIO_PIN_SET)

#define XPT2046_CMD_X 0x90  // X position, differential mode, 12-bit resolution
#define XPT2046_CMD_Y 0xD0  // Y position, differential mode, 12-bit resolution

static uint16_t XPT2046_ReadChannel(uint8_t cmd)
{
    uint8_t tx[3] = { cmd, 0x00, 0x00 };
    uint8_t rx[3] = { 0, 0, 0 };

    TOUCH_CS_LOW();
    HAL_SPI_TransmitReceive(&hspi2, tx, rx, 3, HAL_MAX_DELAY);
    TOUCH_CS_HIGH();

    // XPT2046 returns a 12-bit result sitting in bits [14:3] of a 16-bit window
    uint16_t value = (uint16_t)(((rx[1] << 8) | rx[2]) >> 3);
    return value & 0x0FFF;
}

void Touch_ReadRaw(uint16_t *x, uint16_t *y)
{
    *x = XPT2046_ReadChannel(XPT2046_CMD_X);
    HAL_Delay(1);
    *y = XPT2046_ReadChannel(XPT2046_CMD_Y);
}
